# Generated by Django 4.2.4 on 2023-10-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quikform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=255)),
            ],
        ),
    ]
