# Generated by Django 4.2.4 on 2023-10-17 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_quikform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=255)),
                ('categoria', models.TextField(max_length=255)),
                ('numero_pergunta', models.IntegerField(default=0)),
                ('numero_resposta', models.IntegerField(default=0)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
