# Generated by Django 4.2.4 on 2023-10-17 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_quikform', '0007_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='formulario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_quikform.formulario'),
        ),
    ]
