# Generated by Django 4.2.4 on 2023-11-23 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_quikform', '0008_pergunta_formulario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resposta', models.TextField(max_length=255)),
                ('pergunta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_quikform.pergunta')),
            ],
        ),
    ]
