# Generated by Django 4.2.4 on 2023-11-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quikform', '0011_user_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
